### ISSUE TITLE
Issues with creating empty CountedPtr

### ISSUE THREAD

**Issue by tammojan** [radio-astro-debian/casa-code-debian#15]
https://gist.github.com/tammojan/fa1eb666c5ec50238bdc#file-countedptr-patch

**Comment by gijzelaerr** [comment]
this is for the current trunk version right?

**Comment by tammojan** [comment]
Yes it is. And probably also specific for my current project, so not sure whether it belongs in this list.

**Comment by gijzelaerr** [comment]
thx!
