### ISSUE TITLE
CMake check for Xercesc misses version

### ISSUE THREAD

**Issue by tammojan** [radio-astro-debian/casa-code-debian#16]
Of course my installed version was between 3.0 and 3.2...

https://gist.github.com/tammojan/69062b9684da8ee3c5e7#file-xerces-patch

**Comment by gijzelaerr** [comment]
this is for the current trunk version right?

**Comment by tammojan** [comment]
No it is for release 4.2.0. And is has not been fixed in trunk currently.

**Comment by gijzelaerr** [comment]
thx!
